### ISSUE TITLE
Move application from Linode to Fortrabbit

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#1735]
### Tasks

Overview
- [x] Change how images are stored
- [x] Move all assets stored on disk to S3 https://github.com/monicahq/monica/issues/1742
- [x] Clean useless data in the database (PR: #1829 )
    * the `events` table. we should also remove all the code about `events` in the codebase.
- [x] Add a new app in Fortrabbit
- [x] Copy ENV variables from Forge to the app in Fortrabbit
- [ ] Backup the current DB. I use [Sequel](https://www.sequelpro.com/) to do it.
- [ ] Add the backup of the DB in Fortrabbit.
- [ ] Update DNS in Cloudflare
    * Currently, while our registrar is [Hover](https://www.hover.com/), the DNS is configured in Cloudflare. 
    * See [fortrabbit page about cloudflare](https://help.fortrabbit.com/cloudflare)
- [ ] Setup the cron `php artisan schedule:run` this should run every minute
- [ ] Setup the queue `php artisan queue:work`
- [x] Activate backup of the DB
- [ ] Deprovision Linode
- [ ] Cancel [Forge](https://forge.laravel.com)
- [ ] Deprovision Ottomatik
- [ ] To deploy we can use Envoy as suggested on [Fortrabbit](https://help.fortrabbit.com/install-laravel-5-uni#toc-using-envoy)

### Context
Currently, the application is hosted on Linode. While Linode is a great platform with an extremely fair price and more than decent performances, it comes with the pain of having to manage the server ourselves. If something crashes, good luck with the maintenance.

For more peace of mind, I think we should move to a PAAS like Fortrabbit. The marketing site and version.monicahq.com already use Fortrabbit. They are a good company, with an excellent service and it’s affordable too.

This will let us worry more about the software itself rather than the platform that hosts Monica, and will let me sleep better at night.

### Prerequisite
The only blocking item to make the move is to change how images are stored right now in Monica. This is documented here.

**Comment by djaiss** [comment]
About the DB:
* Backup: we currently use Ottomatik to do hourly backups of the database. If we choose to use the DB provided by Fortrabbit, we need to use their backup option too. We could also investigate whether Amazon RDS would be a good choice for us.

**Comment by asbiin** [comment]
What about papertrailapp log system?
I think laravel has a logging system for parpertrail now, maybe we should use it?

**Comment by djaiss** [comment]
> What about papertrailapp log system?

Good point. I don't know yet.

**Comment by asbiin** [comment]
We need to find a way to store de oauth files (for passport)

**Comment by asbiin** [comment]
* papertrail logging should be solved with #1835
* OAuth (passport) files is solved with #1846

Also linked to this migration:
* ability to define a display application name in emails #1849

**Comment by asbiin** [comment]
We still cannot move to fortrabbit as the are stick on mysql 5.6
