### ISSUE TITLE
Roadmap Q1 2019 (updated Jan 14)

### ISSUE THREAD

**Issue by djaiss** [monicahq/monica#2306]
Here is what @asbiin and I are currently trying to achieve in Q1 2019. This issue is the first of its kind in a tentative of being more transparent with what we try to achieve.

In Q3 and Q4 2018, we've
- built a lot of new features, effectively expanding our features set (which is good)
- not improved the current features (which is not good),
- increased dramatically the code coverage (we are at 67% now),
- made improvements to the CI processes to help us ship a better software,
- increased the number of views built with Vue instead of plain HTML rendered by the backend (which we like, by the way). This helps us have a better UX overall.

---

Our goal in Q1 2019 is to stop creating brand new features and actually improve the current set of features. This is what we will do, in particular:
- [ ] some features should be rewritten with Vue to have a better UX (activities, debts, gifts to name a few)
- [ ] add tiny new details to some core features, making them better. For instance, activities could have places (using Yelp for instance to know where the activity took place) and reminders. Here the goal is to polish what we already have.
- [x] make reminders more robust. They broke too often last year.
- [ ] investigate webhooks. They would make Monica so powerful, but we need to make sure we do it the right way.
- [x] finish support of carddav, which is in beta mode (feedback is appreciated on this). 
- [x] refactor how genders are stored and displayed — this may create a breaking change.
- [ ] add notion of groups : family, co-workers, collocation. Make this work with group carddav. 
- [x] add notion of "me" contact. 
- [ ] write a lot of documentation:
    - [ ] installation procedure (needs some rewrite)
    - [ ] configuration (like .env file)
    - [ ] how to contribute
    - [ ] developper rules
    - [ ] API Documentation

We do have little time every day to devote to this fantastic project, but I think that if we really focus, we can make something great.

**Comment by asbiin** [comment]
@djaiss I think this is overdue
